# Generated by Django 2.2.17 on 2020-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AlterField(
            model_name='studentclassinfo',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
    ]
