# Generated by Django 2.2.17 on 2020-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'father_name', 'mother_name')},
        ),
    ]
