# Generated by Django 2.2.17 on 2020-12-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20201218_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
