# Generated by Django 2.2.17 on 2020-12-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_dob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
