# Generated by Django 2.2.17 on 2020-12-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20201224_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
