# Generated by Django 2.2.17 on 2020-12-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_father'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Father',
        ),
    ]
