# Generated by Django 2.2.17 on 2020-12-31 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
