# Generated by Django 2.2.17 on 2020-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_delete_father'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
