# Generated by Django 2.2.17 on 2020-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassinfo',
            name='class_short_form',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentclassinfo',
            name='class_name',
            field=models.IntegerField(max_length=20),
        ),
    ]
