# Generated by Django 2.2.17 on 2020-12-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherInfo',
            new_name='Teacher',
        ),
    ]
