# Generated by Django 2.2.17 on 2020-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_auto_20201229_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
